travis:
  secure:
    BINSTAR_TOKEN: H1b099MtfUM50tJWnFc4xZ+TwUzdnXu2e6mNNli3rqjsTM7Vw64wS5NBtYKs538pP+5tCx+YC1uINRQgzcHe2LfRtqQLVE9dXLvVrlbYoMQIASpkyQXfgV+ShlQC8gCgAkazS6MONZxPBokX+kqwqV1paZ48s2fBmybAFrt+jzA06z4ZSTJpRQ0zW0hiu5yhRHPvxMN78MkQL0SVMYWn3S20H9NPsBE60NMYTAZ0jKSEo/+ixbsKPwDL/vMv9JnqH9FfBG5LHRXfVXLKUe/hiL0TJtLiWTzluQLgfkDCsWLc4ChRXxpMMVfJCMz9czPY+LiRh9U/BxfQsFbU/kcYqogxZwuAtiVZ8VXkzIHQcRucIgmjFme6EsDqZNHkmC6pozJ+wxzmGuOoMq3YDOqNBhacJtBO1BkynNJ0S8NP79uw0Sj6l/aavxBqWLfRfcltn7tCpisa5ZeWfkS79Zyc2pj1mnhUURW5f3+eOT+Bo8HhnS26Ckd5WSHiIds+20esZxMnXXL+cUymoOHd1GqNjQ64kWQwG1/+HHwAeieNi0Qs+DfuRruvB8p7KDl55cy6QFABad5w6atkPNSzkSzDuJ6CC3rqc+cipf3BV/6fc4+dIndcR98oeH19FE7uLpPT7c+nGs1bHZ3P5aolHnVjfbcXILtqYfvYWzZ3OWX012A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
